export const TOGGLE_EXPORTER_SECTION = 'TOGGLE_EXPORTER_SECTION';
export const SET_EXPORTER_ADVANCED_SETTING = 'SET_EXPORTER_ADVANCED_SETTING';

export const REQUEST_EXPORTER_ADVANCED_SETTINGS = 'REQUEST_EXPORTER_ADVANCED_SETTINGS';
export const REPLY_EXPORTER_ADVANCED_SETTINGS = 'REPLY_EXPORTER_ADVANCED_SETTINGS';

export const REQUEST_START_EXPORT = 'REQUEST_START_EXPORT';
export const REPLY_START_EXPORT = 'REPLY_START_EXPORT';
export const FAIL_EXPORT = 'FAIL_EXPORT';
export const COMPLETE_EXPORT = 'COMPLETE_EXPORT';
